apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keto.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "keto.labels" . | indent 4 }}
  annotations:
    # Create the secret before installation, and only then. This saves the secret from regenerating during an upgrade
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  dsn: {{ include "keto.dsn" . | b64enc | quote }}
